# Data Cleaning

In [ ]:
# import necessary dependancies
import pandas as pd
import matplotlib.pyplot as plt
from glob import glob

## Get data

In [ ]:
def get_data(data):
    datasets =glob(data)
    files=[]
    for dataset in datasets:
        data=pd.read_csv(dataset)
        files.append(data)
    
    return pd.concat(files,ignore_index=True)  

df=get_data("../data/buenos-aires-real-estate-*.csv")

## 5 steps inspection ritual

In [22]:
df.head()

,operation,property_type,place_with_parent_names,lat-lon,price,currency,price_aprox_local_currency,price_aprox_usd,surface_total_in_m2,surface_covered_in_m2,price_usd_per_m2,price_per_m2,floor,rooms,expenses,properati_url
0,sell,house,|Argentina|Bs.As. G.B.A. Zona Oeste|Moreno|Mor...,NaN,180000.0,USD,2729232.0,180000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://moreno.properati.com.ar/10rhr_venta_cas...
1,sell,house,|Argentina|Bs.As. G.B.A. Zona Oeste|Morón|,"-34.6624160375,-58.6044728878",125000.0,USD,1895300.0,125000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://moron-bs-as-g-b-a-zona-oeste.properati....
2,sell,apartment,|Argentina|Bs.As. G.B.A. Zona Sur|Lanús|Lanús|,"-34.7033677191,-58.3923923872",175000.0,USD,2653420.0,175000.0,100.0,92.0,1750.0,1902.173913,NaN,4.0,2.0,http://lanus.properati.com.ar/pzqo_venta_depar...
3,sell,PH,|Argentina|Bs.As. G.B.A. Zona Oeste|La Matanza...,NaN,NaN,NaN,NaN,NaN,199.0,110.0,NaN,NaN,NaN,3.0,NaN,http://ramos-mejia.properati.com.ar/sat2_venta...
4,sell,apartment,|Argentina|Bs.As. G.B.A. Zona Oeste|Ituzaingó|...,NaN,90000.0,USD,1364616.0,90000.0,NaN,70.0,NaN,1285.714286,NaN,3.0,NaN,http://ituzaingo.properati.com.ar/smi9_venta_d...

In [ ]:
df.shape

In [ ]:
df.info()

In [ ]:
df.dtypes

In [ ]:
df.isna().sum()

## Clean data

In [41]:
cleaned_df=(
    df.assign(
        state=lambda x : x["place_with_parent_names"].str.split("|").str[2].astype(str),
         lat=lambda x:x["lat-lon"].str.split(",").str[0].astype(float),
         lon=lambda x:x["lat-lon"].str.split(",").str[1].astype(float)
    ).drop(columns=["place_with_parent_names","lat-lon"])
    .rename(columns={"properati_url":"property_url"})
    
       
    
)

## reinspect

In [42]:
cleaned_df.head()

,operation,property_type,price,currency,price_aprox_local_currency,price_aprox_usd,surface_total_in_m2,surface_covered_in_m2,price_usd_per_m2,price_per_m2,floor,rooms,expenses,property_url,state,lat,lon
0,sell,house,180000.0,USD,2729232.0,180000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://moreno.properati.com.ar/10rhr_venta_cas...,Bs.As. G.B.A. Zona Oeste,NaN,NaN
1,sell,house,125000.0,USD,1895300.0,125000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://moron-bs-as-g-b-a-zona-oeste.properati....,Bs.As. G.B.A. Zona Oeste,-34.662416,-58.604473
2,sell,apartment,175000.0,USD,2653420.0,175000.0,100.0,92.0,1750.0,1902.173913,NaN,4.0,2.0,http://lanus.properati.com.ar/pzqo_venta_depar...,Bs.As. G.B.A. Zona Sur,-34.703368,-58.392392
3,sell,PH,NaN,NaN,NaN,NaN,199.0,110.0,NaN,NaN,NaN,3.0,NaN,http://ramos-mejia.properati.com.ar/sat2_venta...,Bs.As. G.B.A. Zona Oeste,NaN,NaN
4,sell,apartment,90000.0,USD,1364616.0,90000.0,NaN,70.0,NaN,1285.714286,NaN,3.0,NaN,http://ituzaingo.properati.com.ar/smi9_venta_d...,Bs.As. G.B.A. Zona Oeste,NaN,NaN

In [39]:
cleaned_df.shape

(43029, 17)

In [40]:
cleaned_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 43029 entries, 0 to 43028
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   operation                   43029 non-null  str
 1   property_type               43029 non-null  str
 2   price                       38073 non-null  float64
 3   currency                    38072 non-null  str
 4   price_aprox_local_currency  38073 non-null  float64
 5   price_aprox_usd             38073 non-null  float64
 6   surface_total_in_m2         29871 non-null  float64
 7   surface_covered_in_m2       36420 non-null  float64
 8   price_usd_per_m2            24449 non-null  float64
 9   price_per_m2                32642 non-null  float64
 10  floor                       6505 non-null   float64
 11  rooms                       23806 non-null  float64
 12  expenses                    4452 non-null   float64
 13  properati_url               43029 non-null  str
 14  state                       43029 non-null  str
 15  lat                         34734 non-null  float64
 16  lon                         34734 non-null  float64
dtypes: float64(12), str(5)
memory usage: 5.6 MB

In [43]:
cleaned_df.isna().sum()

operation                         0
property_type                     0
price                          4956
currency                       4957
price_aprox_local_currency     4956
price_aprox_usd                4956
surface_total_in_m2           13158
surface_covered_in_m2          6609
price_usd_per_m2              18580
price_per_m2                  10387
floor                         36524
rooms                         19223
expenses                      38577
property_url                      0
state                             0
lat                            8295
lon                            8295
dtype: int64

In [44]:
cleaned_df.to_csv("../data/cleaned_buenos_aires_estate.csv",index=False)