# Data exploration

In [ ]:
# get necessary dependancies
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
# get data
file_path="../data/cleaned_buenos_aires_estate.csv"
data_df=pd.read_csv(file_path)
data_df

In [6]:
data_df.describe()

,price,price_aprox_local_currency,price_aprox_usd,surface_total_in_m2,surface_covered_in_m2,price_usd_per_m2,price_per_m2,floor,rooms,expenses,lat,lon
count,3.807300e+04,3.807300e+04,3.807300e+04,29871.000000,36420.000000,24449.000000,32642.000000,6505.000000,23806.000000,4.452000e+03,34734.000000,34734.000000
mean,2.959661e+05,3.537121e+06,2.332824e+05,269.157578,244.493904,1718.387879,3737.943768,10.789700,3.058305,4.499551e+15,-34.521689,-58.542895
std,4.940386e+05,4.781742e+06,3.153684e+05,1686.328201,10371.179349,1497.571317,11657.891695,79.735358,1.412714,3.002249e+17,2.260135,1.602046
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.056686,1.000000,1.000000,1.000000e+00,-45.857779,-122.419415
25%,9.500000e+04,1.364616e+06,9.000000e+04,47.000000,46.000000,931.372549,1454.545455,2.000000,2.000000,8.000000e+02,-34.642425,-58.582108
50%,1.550000e+05,2.198548e+06,1.450000e+05,90.000000,76.000000,1600.000000,1964.285714,3.000000,3.000000,1.600000e+03,-34.598047,-58.498239
75%,2.950000e+05,3.942224e+06,2.600000e+05,248.000000,160.000000,2193.668000,2666.666667,6.000000,4.000000,3.100000e+03,-34.524870,-58.421971
max,1.500000e+07,2.274360e+08,1.500000e+07,192014.000000,987897.000000,54990.000000,749000.000000,2103.000000,32.000000,2.003200e+19,43.381307,3.379206

In [10]:
data_df[data_df["price"]==0]

,operation,property_type,price,currency,price_aprox_local_currency,price_aprox_usd,surface_total_in_m2,surface_covered_in_m2,price_usd_per_m2,price_per_m2,floor,rooms,expenses,property_url,state,lat,lon
4278,sell,apartment,0.0,NaN,0.0,0.0,NaN,104.0,NaN,NaN,NaN,4.0,NaN,http://general-san-martin-bs-as-g-b-a-zona-nor...,Bs.As. G.B.A. Zona Norte,NaN,NaN
11821,sell,apartment,0.0,ARS,0.0,0.0,NaN,NaN,NaN,NaN,NaN,3.0,NaN,http://belgrano.properati.com.ar/zlmk_venta_de...,Capital Federal,-34.568285,-58.458231
15545,sell,store,0.0,ARS,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://belgrano.properati.com.ar/zr62_venta_lo...,Capital Federal,-34.568285,-58.458231
16394,sell,apartment,0.0,ARS,0.0,0.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,http://belgrano.properati.com.ar/zlmj_venta_de...,Capital Federal,-34.568285,-58.458231
17654,sell,apartment,0.0,ARS,0.0,0.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,http://boedo.properati.com.ar/uyoi_venta_depar...,Capital Federal,-34.626786,-58.425336
20390,sell,apartment,0.0,ARS,0.0,0.0,64.0,NaN,0.0,NaN,NaN,2.0,NaN,http://palermo.properati.com.ar/fi2t_venta_dep...,Capital Federal,-34.583322,-58.446039
28487,sell,apartment,0.0,ARS,0.0,0.0,40.0,NaN,0.0,NaN,NaN,1.0,NaN,http://palermo.properati.com.ar/fi2s_venta_dep...,Capital Federal,-34.583322,-58.446039
35404,sell,apartment,0.0,ARS,0.0,0.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,http://boedo.properati.com.ar/uyoj_venta_depar...,Capital Federal,-34.626786,-58.425336
42353,sell,apartment,0.0,ARS,0.0,0.0,127.0,NaN,0.0,NaN,NaN,3.0,NaN,http://palermo.properati.com.ar/ifor_venta_coc...,Capital Federal,-34.583322,-58.446039